### PR TITLE
vkd3d: Implement fallback when 2D sparse is not supported.

### LINKED ISSUE #1924: Shadow of the Tomb Raider (Epic Version) crashes on DX12 mode
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
Name of the game, settings used etc.

### System information
- GPU: AMD RX 6750XT
- Driver: mesa 24.0.2
- Wine version: GE-Proton8-32
- VKD3D-Proton version: VKD3D built from 3d6aef38c68577667746b0c33ea2950aeb209036
### Log files
[steam-heroic-ShadowoftheTombRaider.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14471238/steam-heroic-ShadowoftheTombRaider.log)

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Relevant for DS sparse on RADV. Convert to a committed resource and pretend all pages are mapped at all times.
Technically out of spec, but should be good enough to work around games until we have proper support.

Fixes #1924.

### CODE REVIEW

File: libs/vkd3d/command.c [hunk 1]
```diff
@@ -16833,6 +16833,13 @@ static void STDMETHODCALLTYPE d3d12_command_queue_UpdateTileMappings(ID3D12Comma
             iface, resource, region_count, region_coords, region_sizes, heap,
             range_count, range_flags, heap_range_offsets, range_tile_counts, flags);
 
+    /* This can be a fallback sparse resource, just ignore any UpdateTileMapping calls on this. */
+    if (!(res->flags & VKD3D_RESOURCE_RESERVED))
+    {
+        FIXME("Ignoring UpdateTileMapping calls on fallback reserved resource.\n");
```
Comment (doitsujin) [inline libs/vkd3d/command.c:16839]: This could get pretty spammy if the app is doing this per frame (or outright broken and calls this on a non-reserved resource), maybe we should demote to `WARN` and do a `FIXME` on resource creation?

**Review by doitsujin — COMMENTED** [review]
nit

File: libs/vkd3d/command.c (hunk 1 above)
Comment (HansKristian-Work) [reply libs/vkd3d/command.c:16839]: ok

Comment (HansKristian-Work) [reply libs/vkd3d/command.c]: Demoted to WARN. I already added FIXME on resource creation.

**Review by doitsujin — APPROVED** [review]
