### PR TITLE
DSV layout fixes

### LINKED ISSUE #2749: Revisit DSV layout tracking shenanigans
The clear fuse work exposed a lot of weakness in the tracking, need to revisit that whole mess.

- Clear fuse does not properly promote optimal layouts.
- DSV images with layers > 1 or mips > 1 seem to have some weakness where we don't get the correct optimal layout in all cases. Needs more test cases ...

Ideally we should be able to get rid of all this mess.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Surely we'll get it right this time :frog:

Fix #2749.

### CODE REVIEW

File: libs/vkd3d/command.c [hunk 1]
```diff
@@ -6832,7 +6850,7 @@ static bool d3d12_command_list_update_rendering_info(struct d3d12_command_list *
     {
         assert(list->dsv.view);
 
-        dsv_optimal_aspects = 0u;
+        dsv_aspects = 0u;
```
Comment (doitsujin) [inline libs/vkd3d/command.c]: this is equivalent to `list->dsv.view->format->vk_aspect_mask` now and can probably be removed.

Comment (HansKristian-Work) [reply libs/vkd3d/command.c]: Fixed.

**Review by doitsujin — APPROVED** [review]
