### PR TITLE
Workaround broken VRS in Dead Space remaster

### LINKED ISSUE #1398: Dead Space: RSSetShadingRateImage called with invalid resource for VRS.
This warning is spammed in Dead Space. The resource is rejected for VRS because it was created with the flag `ALLOW_RENDER_TARGET`. According to the docs this flag is not allowed for VRS images.

> These flags are not permitted.
> ALLOW_RENDER_TARGET
> ALLOW_DEPTH_STENCIL
> ALLOW_CROSS_ADAPTER
> ALLOW_SIMULTANEOUS_ACCESS
> VIDEO_DECODE_REFERENCE_ONLY

https://learn.microsoft.com/en-us/windows/win32/direct3d12/vrs

There's three options here:

- this isn't enforced and works fine despite what the docs say
- this changed with a newer Agility SDK release and the docs are out of date
- this is a game bug and doesn't work on Windows either.

I've tried removing `ALLOW_RENDER_TARGET` from the VRS check and the game worked fine and was slightly faster.

### PR DESCRIPTION
**Pull request by HansKristian-Work**
Fix #1398.

### CODE REVIEW

File: libs/vkd3d/resource.c [hunk 1]
```diff
@@ -778,6 +782,16 @@ HRESULT vkd3d_get_image_allocation_info(struct d3d12_device *device,
...
     allocation_info->Alignment = requirements.memoryRequirements.alignment;
 
+    /* If we might create an image with VRS usage, need to also check memory requirements without VRS usage.
+     * VRS usage can depend on heap properties and this can affect compression, tile layouts, etc. */
+    if (create_info.image_info.usage & VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR)
+    {
+        create_info.image_info.usage &= ~VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR;
+        VK_CALL(vkGetDeviceImageMemoryRequirementsKHR(device->vk_device, &requirement_info, &requirements));
+        allocation_info->SizeInBytes = max(requirements.memoryRequirements.size, allocation_info->SizeInBytes);
+        allocation_info->Alignment = max(requirements.memoryRequirements.alignment, allocation_info->Alignment);
```
Comment (doitsujin) [inline libs/vkd3d/resource.c:792]: We might need to realign the reported size to the new alignment as well in case the VRS alignment is smaller but size is larger than the old values.

Comment (HansKristian-Work) [reply libs/vkd3d/resource.c:792]: Not sure I follow we do max here for both cases. What are the potential returned values that can cause issues here?

Comment (doitsujin) [reply libs/vkd3d/resource.c:792]: Say old alignment is 64k, old size is 64k, VRS alignment is 32k and VRS size is 96k, then we end up with new alignment 64k but new size 96k, but we'd need to return a size of 128k.

Probably won't ever happen in practice though.

Comment (HansKristian-Work) [reply libs/vkd3d/resource.c:792]: So the requirement is that returned size must align? Not sure where that requirement is stated.

Comment (doitsujin) [reply libs/vkd3d/resource.c:792]: Turns out we're already doing this elsewhere anyway, so nevermind.

**Review by doitsujin — APPROVED** [review]
