### PR TITLE
vkd3d-shader: Merge i/o variables using the same location.

### LINKED ISSUE #609: Terrain misrendering in Anno 1800 (and poor performance)
When using the D3D12 renderer of Anno 1800, the terrain seems to be composed of multiples blocky textures.
All of this was tested on a RX 570 4GB VRAM.

This bug is present with RADV as well as AMDVLK.

Also note that the game will crash in a few seconds after starting a game with both AMDVLK and Windows 
driver. RADV looks stable.

There is also an issue with performance often being bad (~15fps instead of 40 with DXVK on a specific place). I suspect is has something to do VRAM limitation as it doesn't happen when using low quality texture instead of high. MangoHud shows that VRAM is used at near 4GB, even with low quality textures. I don't have this issue is both DXVK and windows D3D12. 
Can't tell for sure as the game crash fast on Windows, but I haven't encountered this performance issue on windows VKD3D.

RADV is using mesa 21.0 from kisak ppa.
VKD3D log at "warn" level: 
[vkd3d_anno1800_radv.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/6275310/vkd3d_anno1800_radv.txt)
Tested on both VKD3D 2.2 (from Proton 6.3-2) and VKD3D git.
Tested on Proton 6.3-2

### PR DESCRIPTION
**Pull request by doitsujin**
Fixes #609.

### CODE REVIEW

File: libs/vkd3d-shader/spirv.c [hunk 1]
```diff
@@ -4420,23 +4441,116 @@ static bool needs_private_io_variable(const struct vkd3d_shader_signature *signa
...
+    {
+        vkd3d_spirv_build_op_decorate1(builder, var_id, SpvDecorationLocation, 0);
+        vkd3d_spirv_build_op_decorate1(builder, var_id, SpvDecorationIndex, location);
+    }
+    else
+    {
+        vkd3d_spirv_build_op_decorate1(builder, var_id, SpvDecorationLocation, location);
+    }
+
+    if (compiler->shader_type == VKD3D_SHADER_TYPE_PIXEL && storage_class == SpvStorageClassInput)
```
Comment (HansKristian-Work) [inline libs/vkd3d-shader/spirv.c:4541]: Might make more sense to decorate Patch here, considering there's an early out for `var_ids`?

File: libs/vkd3d-shader/spirv.c [hunk 2]
```diff
@@ -5085,6 +5148,10 @@ static void vkd3d_dxbc_compiler_emit_output(struct vkd3d_dxbc_compiler *compiler
 
     compiler->output_info[signature_idx].id = id;
     compiler->output_info[signature_idx].component_type = component_type;
+    compiler->output_info[signature_idx].dst_write_mask = (VKD3DSP_WRITEMASK_0 << output_component_count) - 1;
+
+    if (!builtin)
```
Comment (HansKristian-Work) [inline libs/vkd3d-shader/spirv.c:5153]: Not sure I understand the rationale behind this. Are there cases where write_mask would be smaller than num_components? Would that happen if multiple signature outputs share the same physical IO variable?

File: libs/vkd3d-shader/spirv.c (hunk 1 above)
Comment (doitsujin) [reply libs/vkd3d-shader/spirv.c:4541]: Yeah, oversight.
