### PR TITLE
Planar formats, part 3: Implement planar formats

### LINKED ISSUE #2021: Kingdom Hearts -HD 1.5+2.5 ReMix- New Game videos do not work
The intro video after starting a new game on Kingdom Hearts as part of the Kingdom Hearts -HD 1.5+2.5 ReMix-
 collection only displays a black screen. Audio displays correctly. This only happens when the game is not detected as a Steam Deck. The intro video is using NV12 by default, and is using X8R8G8B8 for when a Steam Deck is detected.

### Software information
Kingdom Hearts -HD 1.5+2.5 ReMix- was the only one tested, and only on the first game. I have a feeling it will affect the intro video in all the games in this collection, with a good chance Kingdom Hearts HD 2.8 Final Chapter Prologue and Kingdom Hearts III + Re Mind (DLC) also having the intro videos.

Default settings.

### System information
- GPU: AMD 7900XT
- Proton version: experimental-bleeding-edge-9.0-102532-20240613-pc167f9-wa4bf20-da8710f-vb4eb56

### Log files
This log file has additional media channels used.

[Exp-Desktop-Detected-Blackscreen-at-video-steam-2552430_1.log](https://github.com/user-attachments/files/15930768/Exp-Desktop-Detected-Blackscreen-at-video-steam-2552430_1.log)

### PR DESCRIPTION
**Pull request by doitsujin**
Draft for now since this depends on #2028.

Adds support for NV12, P010 and P016 formats, which are pretty much all the planar formats available in D3D12 (`420_OPAQUE` exists, but can only be used with video APIs).

Should fix #2021.

### CODE REVIEW

File: libs/vkd3d/utils.c [hunk 1]
```diff
@@ -28,9 +28,23 @@
 #define DEPTH         (VK_IMAGE_ASPECT_DEPTH_BIT)
 #define STENCIL       (VK_IMAGE_ASPECT_STENCIL_BIT)
 #define DEPTH_STENCIL (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT)
+#define PLANAR        (VK_IMAGE_ASPECT_PLANE_0_BIT | VK_IMAGE_ASPECT_PLANE_1_BIT)
 #define TYPELESS      VKD3D_FORMAT_TYPE_TYPELESS
 #define SINT          VKD3D_FORMAT_TYPE_SINT
 #define UINT          VKD3D_FORMAT_TYPE_UINT
+
+static const struct vkd3d_format_footprint nv12_copy_footprints[] =
```
Comment (HansKristian-Work) [inline libs/vkd3d/utils.c:36]: iirc, this breaks on some C compilers. At least MSVC tends to complain here.

Comment (HansKristian-Work) [reply libs/vkd3d/utils.c:36]: Seems like we've already used this pattern for ages below in the file, so, eh, whatever.

Comment (doitsujin) [reply libs/vkd3d/utils.c:36]: what exactly does it complain about?

Comment (HansKristian-Work) [reply libs/vkd3d/utils.c:36]: It's the classic problem where a static const variable is not considered a compile time constant, so using a static const variable to feed a new static const variable would break, but it seems to work here, so ... *shrug* I just remember we had issues with that in the shader headers a while back.

**Review by HansKristian-Work — APPROVED** [review]
LGTM
